from app.agents.prompts.planning import PLANNING_SYSTEM, PLANNING_USER, REFINE_QUERIES_SYSTEM, REFINE_QUERIES_USER
from app.agents.prompts.filter import FILTER_SYSTEM, FILTER_USER
from app.agents.prompts.synthesis import SYNTHESIS_SYSTEM, SYNTHESIS_USER
from app.agents.prompts.draft import DRAFT_SYSTEM, DRAFT_USER
from app.agents.prompts.evaluation import (
    EVALUATE_QUALITY_SYSTEM, EVALUATE_QUALITY_USER,
    EVALUATE_COVERAGE_SYSTEM, EVALUATE_COVERAGE_USER,
    EVALUATE_REPORT_SYSTEM, EVALUATE_REPORT_USER,
)

__all__ = [
    "PLANNING_SYSTEM", "PLANNING_USER", "REFINE_QUERIES_SYSTEM", "REFINE_QUERIES_USER",
    "FILTER_SYSTEM", "FILTER_USER",
    "SYNTHESIS_SYSTEM", "SYNTHESIS_USER",
    "DRAFT_SYSTEM", "DRAFT_USER",
    "EVALUATE_QUALITY_SYSTEM", "EVALUATE_QUALITY_USER",
    "EVALUATE_COVERAGE_SYSTEM", "EVALUATE_COVERAGE_USER",
    "EVALUATE_REPORT_SYSTEM", "EVALUATE_REPORT_USER",
]
